/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/services/triggerService`; params?: Router.UnknownInputParams; } | { pathname: `/services/reviewService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/conta` | `/conta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/novoGatilho` | `/novoGatilho`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/revisar` | `/revisar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre` | `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/services/triggerService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/reviewService`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/conta` | `/conta`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/novoGatilho` | `/novoGatilho`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/revisar` | `/revisar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sobre` | `/sobre`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/services/triggerService${`?${string}` | `#${string}` | ''}` | `/services/reviewService${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/conta${`?${string}` | `#${string}` | ''}` | `/conta${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/novoGatilho${`?${string}` | `#${string}` | ''}` | `/novoGatilho${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/revisar${`?${string}` | `#${string}` | ''}` | `/revisar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sobre${`?${string}` | `#${string}` | ''}` | `/sobre${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/services/triggerService`; params?: Router.UnknownInputParams; } | { pathname: `/services/reviewService`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/conta` | `/conta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/novoGatilho` | `/novoGatilho`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/revisar` | `/revisar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre` | `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
